// <auto-generated />
using System;
using CERTHB2B.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CERTHB2B.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200526142918_BusinessProfiles")]
    partial class BusinessProfiles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CERTHB2B.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "818e3ae4-dfaa-4e2e-a042-2db203e8febb",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dd4f1dee-d24b-4e68-b408-c9375c624989",
                            Email = "admin@nekya.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN@NEKYA.COM",
                            NormalizedUserName = "ADMIN@NEKYA.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEHzf5sE4/pDew5etQujm8dO/17HHohsdhX84KD8PrlWVdpNdRrwRVuDDp06Af8lA0Q==",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2020, 5, 26, 11, 23, 40, 221, DateTimeKind.Utc),
                            SecurityStamp = "CEAA272E6A8028468585E33BEE7402BB",
                            TwoFactorEnabled = false,
                            UserName = "admin@nekya.com"
                        },
                        new
                        {
                            Id = "bedbc467-6cd4-4342-8658-851556be8ce0",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0063de9c-29c3-4f58-bb27-8691f18811f8",
                            Email = "editor@nekya.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            LockoutEnd = new DateTimeOffset(new DateTime(2070, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            NormalizedEmail = "EDITOR@NEKYA.COM",
                            NormalizedUserName = "EDITOR@NEKYA.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAENt08bjzGZwulojjOeJZ4ilqVN9ATxdXxj6qPvO2V/6B0culdHIRCFaxMPCTjg0eSQ==",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2020, 5, 26, 11, 23, 40, 221, DateTimeKind.Utc),
                            SecurityStamp = "DC8A808B01077C43B268EAE077B7EC2E",
                            TwoFactorEnabled = false,
                            UserName = "editor@nekya.com"
                        },
                        new
                        {
                            Id = "182651c4-7698-4745-ad3e-207edba16b1e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "39b8e7f7-9b5d-4abd-826c-4af31d77f229",
                            Email = "user@nekya.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            LockoutEnd = new DateTimeOffset(new DateTime(2070, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            NormalizedEmail = "USER@NEKYA.COM",
                            NormalizedUserName = "USER@NEKYA.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEJNDFzILfnoH3q61fJAwYdTjd+a47AzAVqpvijjS4uyaAbAOjWYNER7J60HYtaLl3Q==",
                            PhoneNumberConfirmed = false,
                            RegistrationDate = new DateTime(2020, 5, 26, 11, 23, 40, 221, DateTimeKind.Utc),
                            SecurityStamp = "9D96BC88CAC7BC479DA8B901743749BF",
                            TwoFactorEnabled = false,
                            UserName = "user@nekya.com"
                        });
                });

            modelBuilder.Entity("CERTHB2B.Models.BusinessActivitiesOptions", b =>
                {
                    b.Property<long>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActivityOptionAlias")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.HasKey("ActivityId");

                    b.HasAlternateKey("ActivityOptionAlias");

                    b.ToTable("BusinessActivitiesOptions");

                    b.HasData(
                        new
                        {
                            ActivityId = 1L,
                            ActivityOptionAlias = "TopicsOfInterest.CleanPowerTransport.$Electromobility"
                        },
                        new
                        {
                            ActivityId = 2L,
                            ActivityOptionAlias = "TopicsOfInterest.CleanPowerTransport.$MicroMobility"
                        },
                        new
                        {
                            ActivityId = 3L,
                            ActivityOptionAlias = "TopicsOfInterest.CleanPowerTransport.$Biofuels"
                        },
                        new
                        {
                            ActivityId = 4L,
                            ActivityOptionAlias = "TopicsOfInterest.CleanPowerTransport.$HydrogenMobility"
                        },
                        new
                        {
                            ActivityId = 5L,
                            ActivityOptionAlias = "TopicsOfInterest.AirMobility.$DronesManufacturing"
                        },
                        new
                        {
                            ActivityId = 6L,
                            ActivityOptionAlias = "TopicsOfInterest.AirMobility.$DronesTrading"
                        },
                        new
                        {
                            ActivityId = 7L,
                            ActivityOptionAlias = "TopicsOfInterest.Logistics.$LastmileLogistics"
                        },
                        new
                        {
                            ActivityId = 8L,
                            ActivityOptionAlias = "TopicsOfInterest.Logistics.$DronesApplicationsForLogistics"
                        },
                        new
                        {
                            ActivityId = 9L,
                            ActivityOptionAlias = "TopicsOfInterest.UrbanMobility.$SharedMobility"
                        },
                        new
                        {
                            ActivityId = 10L,
                            ActivityOptionAlias = "TopicsOfInterest.UrbanMobility.$TrafficManagementSystems"
                        },
                        new
                        {
                            ActivityId = 11L,
                            ActivityOptionAlias = "TopicsOfInterest.TransportInfrastructure.$RailInfrastructure"
                        },
                        new
                        {
                            ActivityId = 12L,
                            ActivityOptionAlias = "TopicsOfInterest.TransportInfrastructure.$RoadInfrastructure"
                        },
                        new
                        {
                            ActivityId = 13L,
                            ActivityOptionAlias = "TopicsOfInterest.TransportInfrastructure.$MaritimeInfrastructure"
                        },
                        new
                        {
                            ActivityId = 14L,
                            ActivityOptionAlias = "TopicsOfInterest.TransportInfrastructure.$AirTransportInfrastructure"
                        },
                        new
                        {
                            ActivityId = 15L,
                            ActivityOptionAlias = "TopicsOfInterest.Automotive.$ElectricVehiclesManufacturing"
                        },
                        new
                        {
                            ActivityId = 16L,
                            ActivityOptionAlias = "TopicsOfInterest.Automotive.$ElectricVehiclesTrading"
                        },
                        new
                        {
                            ActivityId = 17L,
                            ActivityOptionAlias = "TopicsOfInterest.Automotive.$AutonomousVehiclesManufacturing"
                        },
                        new
                        {
                            ActivityId = 18L,
                            ActivityOptionAlias = "TopicsOfInterest.Automotive.$AutonomousVehiclesTrading"
                        },
                        new
                        {
                            ActivityId = 19L,
                            ActivityOptionAlias = "TopicsOfInterest.ICTTransport.$ITSSystems"
                        },
                        new
                        {
                            ActivityId = 20L,
                            ActivityOptionAlias = "TopicsOfInterest.ICTTransport.$CITSSystems"
                        },
                        new
                        {
                            ActivityId = 21L,
                            ActivityOptionAlias = "TopicsOfInterest.ICTTransport.$DataAnalyticsTransport"
                        },
                        new
                        {
                            ActivityId = 22L,
                            ActivityOptionAlias = "TopicsOfInterest.$TransportPolicy"
                        },
                        new
                        {
                            ActivityId = 23L,
                            ActivityOptionAlias = "TopicsOfInterest.$ConsultingServices"
                        },
                        new
                        {
                            ActivityId = 24L,
                            ActivityOptionAlias = "Offer.Collaboration.$ForFundingCall"
                        },
                        new
                        {
                            ActivityId = 25L,
                            ActivityOptionAlias = "Offer.Collaboration.$DevelopNewProduct"
                        },
                        new
                        {
                            ActivityId = 26L,
                            ActivityOptionAlias = "Offer.Collaboration.$DevelopNewService"
                        },
                        new
                        {
                            ActivityId = 27L,
                            ActivityOptionAlias = "Offer.$TechnicalCooperation"
                        },
                        new
                        {
                            ActivityId = 28L,
                            ActivityOptionAlias = "Offer.ConsultingServices.$BusinessConsultingServices"
                        },
                        new
                        {
                            ActivityId = 29L,
                            ActivityOptionAlias = "Offer.ConsultingServices.$TransportRelatedConsultingServices"
                        },
                        new
                        {
                            ActivityId = 30L,
                            ActivityOptionAlias = "Request.Collaboration.$ForFundingCall"
                        },
                        new
                        {
                            ActivityId = 31L,
                            ActivityOptionAlias = "Request.Collaboration.$DevelopNewProduct"
                        },
                        new
                        {
                            ActivityId = 32L,
                            ActivityOptionAlias = "Request.Collaboration.$DevelopNewService"
                        },
                        new
                        {
                            ActivityId = 33L,
                            ActivityOptionAlias = "Request.Supplier.$ForComponents"
                        },
                        new
                        {
                            ActivityId = 34L,
                            ActivityOptionAlias = "Request.Supplier.$ForServices"
                        },
                        new
                        {
                            ActivityId = 35L,
                            ActivityOptionAlias = "Request.Supplier.$ForData"
                        },
                        new
                        {
                            ActivityId = 36L,
                            ActivityOptionAlias = "Request.ConsultingServices.$BusinessConsultingServices"
                        },
                        new
                        {
                            ActivityId = 37L,
                            ActivityOptionAlias = "Request.ConsultingServices.$TransportRelatedConsultingServices"
                        });
                });

            modelBuilder.Entity("CERTHB2B.Models.BusinessAddress", b =>
                {
                    b.Property<long>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressId");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("BusinessAddress");
                });

            modelBuilder.Entity("CERTHB2B.Models.BusinessContact", b =>
                {
                    b.Property<long>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("BusinessContact");
                });

            modelBuilder.Entity("CERTHB2B.Models.BusinessProfile", b =>
                {
                    b.Property<long>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsProfileVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProfileId");

                    b.HasIndex("UserId");

                    b.ToTable("BusinessProfiles");
                });

            modelBuilder.Entity("CERTHB2B.Models.BusinessProfileActivities", b =>
                {
                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.Property<long>("ActivityId")
                        .HasColumnType("bigint");

                    b.HasKey("ProfileId", "ActivityId");

                    b.ToTable("BusinessProfileActivities");
                });

            modelBuilder.Entity("CERTHB2B.Models.BusinessProfileOtherActivities", b =>
                {
                    b.Property<long>("OtherActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActivityAlias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.HasKey("OtherActivityId");

                    b.HasIndex("ProfileId");

                    b.ToTable("BusinessProfileOtherActivities");
                });

            modelBuilder.Entity("CERTHB2B.Models.ContentBlock", b =>
                {
                    b.Property<long>("BlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BindToContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Locked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("BlockId");

                    b.ToTable("ContentBlock");
                });

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.DeviceFlowCodes", b =>
                {
                    b.Property<string>("UserCode")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(50000);

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime?>("Expiration")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("SubjectId")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("UserCode");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("Expiration");

                    b.ToTable("DeviceCodes");
                });

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.PersistedGrant", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(50000);

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubjectId")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Key");

                    b.HasIndex("Expiration");

                    b.HasIndex("SubjectId", "ClientId", "Type");

                    b.ToTable("PersistedGrants");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "24d76187-397c-44aa-bc45-1970ae5adcf3",
                            ConcurrencyStamp = "d79bb754-16ca-4417-b106-31951e2fb671",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "97c19e19-d4ce-46e7-922b-cc954cfe531d",
                            ConcurrencyStamp = "7409dfa1-0a1d-4c65-89e9-d04ab259ec03",
                            Name = "Editor",
                            NormalizedName = "EDITOR"
                        },
                        new
                        {
                            Id = "540cf8e7-57d9-4b81-bb5a-898c7f7649c1",
                            ConcurrencyStamp = "458b4ba1-a711-43dd-b0ea-ea0c930214bb",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "818e3ae4-dfaa-4e2e-a042-2db203e8febb",
                            RoleId = "24d76187-397c-44aa-bc45-1970ae5adcf3"
                        },
                        new
                        {
                            UserId = "bedbc467-6cd4-4342-8658-851556be8ce0",
                            RoleId = "97c19e19-d4ce-46e7-922b-cc954cfe531d"
                        },
                        new
                        {
                            UserId = "182651c4-7698-4745-ad3e-207edba16b1e",
                            RoleId = "540cf8e7-57d9-4b81-bb5a-898c7f7649c1"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("CERTHB2B.Models.BusinessAddress", b =>
                {
                    b.HasOne("CERTHB2B.Models.BusinessProfile", "Profile")
                        .WithOne("CompanyLocation")
                        .HasForeignKey("CERTHB2B.Models.BusinessAddress", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CERTHB2B.Models.BusinessContact", b =>
                {
                    b.HasOne("CERTHB2B.Models.BusinessProfile", "Profile")
                        .WithOne("ContactPerson")
                        .HasForeignKey("CERTHB2B.Models.BusinessContact", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CERTHB2B.Models.BusinessProfile", b =>
                {
                    b.HasOne("CERTHB2B.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("CERTHB2B.Models.BusinessProfileActivities", b =>
                {
                    b.HasOne("CERTHB2B.Models.BusinessProfile", "Profile")
                        .WithMany("Activities")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CERTHB2B.Models.BusinessProfileOtherActivities", b =>
                {
                    b.HasOne("CERTHB2B.Models.BusinessProfile", "Profile")
                        .WithMany("OtherActivities")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.HasOne("CERTHB2B.Models.ApplicationUser", null)
                        .WithMany("Roles")
                        .HasForeignKey("ApplicationUserId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CERTHB2B.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CERTHB2B.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CERTHB2B.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CERTHB2B.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
